sudo: false

language: cpp
compiler: clang

script:
    - python3 misc/test_zlib_debug_compressor.py
    - mkdir -p build
    - cd build
    - clang -O2 ../misc/fuzz_deflate.c -o fuzz_deflate
    - clang -O2 ../misc/test_deflate.c -o test_deflate
    - python3 ../misc/test_deflate.py ./test_deflate ..
    - clang -O2 -std=gnu99 -Wno-unused-value -D_GNU_SOURCE ../test/runner.c -o runner
    - ./runner -v
    - clang -coverage -g -std=gnu99 -Wno-unused-value -D_GNU_SOURCE ../test/runner.c -o runner
    - ./runner -v
    - llvm-cov gcov runner
    - cp ufbx_implementation.h.gcov ../ufbx_implementation.h.gcov
    - rm *.gcov

after_success:
    - bash <(curl -s https://codecov.io/bash) -X gcov
