sudo: false

language: cpp
compiler: clang

script:
    - mkdir -p build
    - cd build
    - clang ../test/runner.c -fprofile-instr-generate -fcoverage-mapping -g -std=gnu99 -Wno-unused-value -o runner -D_GNU_SOURCE
    - LLVM_PROFILE_FILE=runner.prowraw ./runner -v
    - llvm-profdata merge -sparse runner.profraw -o runner.profdata
    - llvm-cov show ./runner -instr-profile=runner.profdata
