language: cpp
compiler: clang

script:
    - python3 misc/test_zlib_debug_compressor.py
    - mkdir -p build
    - cd build
    - clang -lm -O2 ../misc/fuzz_deflate.c -o fuzz_deflate
    - clang -lm -O2 ../misc/test_deflate.c -o test_deflate
    - clang++ -lm ../misc/test_build.cpp -o test_build_cpp
    - python3 ../misc/test_deflate.py ./test_deflate ..
    - clang -lm -O2 -std=gnu99 -Wno-unused-value -D_GNU_SOURCE ../ufbx.c ../test/runner.c -o runner
    - ./runner -v -d ../data
    - clang -lm -coverage -g -std=gnu99 -Wno-unused-value -D_GNU_SOURCE ../ufbx.c ../test/runner.c -o runner
    - ./runner -v -d ../data/
    - llvm-cov gcov ufbx -a -b
    - cp ufbx.c.gcov ../ufbx.c.gcov
    - rm *.gcov

after_success:
    - bash <(curl -s https://codecov.io/bash) -X gcov
