sudo: false

language: cpp
compiler: clang

script:
    - mkdir -p build
    - cd build
    - clang ../test/runner.c --coverage -g -std=gnu99 -Wno-unused-value -o runner -D_GNU_SOURCE
    - ./runner -v
    - llvm-cov show .
