sudo: false

language: cpp
compiler: clang

script:
    - mkdir -p build
    - cd build
    - clang -coverage -g -std=gnu99 -Wno-unused-value -D_GNU_SOURCE ../test/runner.c -o runner
    - ./runner -v
    - llvm-cov gcov runner

after_success:
    - bash <(curl -s https://codecov.io/bash) -s build -X gcov
