name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  ci_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install apt dependencies
        run: sudo apt install -y gcc-multilib g++-multilib lcov llvm-9
      - name: Run tests
        run: python3 misc/run_tests.py
      - name: Verbose test info
        run: build/runner_clang_release_x64/runner -d data -v
      - name: Generate coverage
        run: LLVM_COV=llvm-cov-9 bash misc/generate_coverage.sh
      - name: Upload coverage
        run: bash <(curl -s https://codecov.io/bash) -f coverage.lcov -y misc/codecov.yml

  ci_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: python misc/run_tests.py
      - name: Verbose test info
        run: build\runner_vs_cl64_release_x64\runner.exe -d data -v
