name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Cancel any in-flight jobs for the same PR/branch so there's only one active
# at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  ci_pre_hashes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Compile hash_scene
        run: |
          mkdir build
          clang test/hash_scene.c misc/fdlibm.c -O2 -o build/hash_scene
      - name: Generate reference hashes
        run: |
          python3 misc/generate_hashses.py --exe build/hash_scene -o build/hashes.txt --verbose
      - uses: actions/upload-artifact@v3
        with:
          name: reference-hashes
          path: build/hashes.txt

  ci_ubuntu:
    runs-on: ubuntu-latest
    needs: ci_pre_hashes
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Update apt
        run: sudo apt-get update
      - name: Install apt dependencies
        run: sudo apt-get install -y gcc-multilib g++-multilib lcov llvm-11
      - uses: actions/download-artifact@v3
        with:
          name: reference-hashes
          path: build/hashes.txt
      - name: Run tests
        run: python3 misc/run_tests.py tests readme threadcheck hashes
      - name: Compress hashdumps
        if: ${{ always() && !cancelled() }}
        run: python3 misc/hash_diff.py compress build/hashdumps -o build/hashdump_ci_linux.txt.gz
      - uses: actions/upload-artifact@v3
        if: ${{ always() && !cancelled() }}
        with:
          name: hashdumps
          path: build/hashdump_ci_linux.txt.gz
      - name: Verbose test info
        run: build/runner_clang_release_x64/runner -d data -v
      - name: Generate coverage
        run: LLVM_COV=llvm-cov-11 bash misc/generate_coverage.sh
      - name: Upload coverage
        run: bash <(curl -s https://codecov.io/bash) -f coverage.lcov -y .github/codecov.yml

  ci_windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: python misc/run_tests.py tests readme threadcheck
      - name: Verbose test info
        run: build\runner_vs_cl64_release_x64\runner.exe -d data -v

  ci_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: python3 misc/run_tests.py tests readme threadcheck --remove-compiler gcc --additional-compiler gcc-11 --remove-arch x86
      - name: Compile ufbx as Objective C
        run: clang -Wall -Wextra -Werror -ObjC -c ufbx.c -o build/ufbx-objc.o

  ci_picort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run picort
        run: python misc/run_tests.py picort
      - name: Upload result images
        env:
          BUNNY_API_TOKEN: ${{ secrets.BUNNY_API_TOKEN }}
        if: ${{ always() && !cancelled() }}
        continue-on-error: true
        run: |
          HASH="$(git rev-parse --short=16 HEAD)"
          URL="https://storage.bunnycdn.com/ufbx-images/$HASH"
          DST_URL="https://ufbx-images.b-cdn.net/$HASH"
          curl -sS -w " -> $DST_URL/barbarian.png \n" --request PUT --header "AccessKey: $BUNNY_API_TOKEN" --header "Content-Type: image/png" --url $URL/barbarian.png --data-binary @build/images/barbarian.png
          curl -sS -w " -> $DST_URL/barbarian-scalar.png \n" --request PUT --header "AccessKey: $BUNNY_API_TOKEN" --header "Content-Type: image/png" --url $URL/barbarian-scalar.png --data-binary @build/images/barbarian-scalar.png
          curl -sS -w " -> $DST_URL/barbarian-big.png \n" --request PUT --header "AccessKey: $BUNNY_API_TOKEN" --header "Content-Type: image/png" --url $URL/barbarian-big.png --data-binary @build/images/barbarian-big.png
          curl -sS -w " -> $DST_URL/slime-binary.png \n" --request PUT --header "AccessKey: $BUNNY_API_TOKEN" --header "Content-Type: image/png" --url $URL/slime-binary.png --data-binary @build/images/slime-binary.png
          curl -sS -w " -> $DST_URL/slime-ascii.png \n" --request PUT --header "AccessKey: $BUNNY_API_TOKEN" --header "Content-Type: image/png" --url $URL/slime-ascii.png --data-binary @build/images/slime-ascii.png
          curl -sS -w " -> $DST_URL/slime-big.png \n" --request PUT --header "AccessKey: $BUNNY_API_TOKEN" --header "Content-Type: image/png" --url $URL/slime-big.png --data-binary @build/images/slime-big.png

  ci_domfuzz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run domfuzz
        run: python misc/run_tests.py domfuzz

  ci_viewer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run viewer
        run: python misc/run_tests.py viewer

  ci_features:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile feature permutaitons
        run: python misc/run_tests.py features

  ci_analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update apt
        run: sudo apt-get update
      - name: Install apt dependencies
        run: sudo apt-get install -y cppcheck
      - name: cppcheck
        run: cppcheck --error-exitcode=1 --inline-suppr --std=c99 ufbx.c -DUFBX_STATIC_ANALYSIS=1
      - name: Clang Analyzer
        if: ${{ always() && !cancelled() }}
        run: clang --analyze -Xanalyzer -analyzer-werror -Xanalyzer -analyzer-disable-checker=unix.Malloc ufbx.c

  ci_exotic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update apt
        run: sudo apt-get update
      - name: Install apt dependencies
        run: sudo apt-get install -y tcc qemu qemu-user gcc-multilib
      - name: Install zig cc via PIP
        run: sudo pip3 install ziglang
      - name: Run tests with TCC
        run: python3 misc/run_tests.py tests --additional-compiler tcc --compiler tcc --remove-arch x86
      - name: Compile ufbx.c wth x86 TCC
        run: i386-tcc -Wall -Werror -c ufbx.c -o build/tcc-ufbx-x86.o
      - name: Compile PowerPC tests
        run: python3 -m ziglang cc -fno-sanitize=undefined -target powerpc-linux ufbx.c test/runner.c -g -o build/ppc-runner
      - name: Run PowerPC tests
        run: qemu-ppc build/ppc-runner -d data
      - name: Compile runner.c
        run: gcc -c test/runner.c -o build/runner.o
      - name: Build and run standard C99
        run: |
          gcc -Wall -Wextra -Werror -std=c99 -DUFBX_STANDARD_C build/runner.o ufbx.c -lm -o build/runner-c99
          build/runner-c99 -d data --allow-non-thread-safe
      - name: Build and run standard C11
        run: |
          gcc -Wall -Wextra -Werror -std=c11 -DUFBX_STANDARD_C build/runner.o ufbx.c -lm -o build/runner-c11
          build/runner-c11 -d data
      - name: Build and run standard C++98
        run: |
          g++ -Wall -Wextra -Werror -std=c++98 -DUFBX_STANDARD_C build/runner.o -x c++ ufbx.c -lm -o build/runner-cpp98
          build/runner-cpp98 -d data --allow-non-thread-safe
      - name: Build and run standard C++11
        run: |
          g++ -Wall -Wextra -Werror -std=c++11 -DUFBX_STANDARD_C build/runner.o -x c++ ufbx.c -lm -o build/runner-cpp11
          build/runner-cpp11 -d data
      - name: Build and run threadcheck (standard C11)
        run: |
          gcc -Wall -Wextra -Werror -std=c11 -DUFBX_STANDARD_C -c ufbx.c -o build/ufbx-c11.o
          g++ -Wall -Wextra -Werror -pthread -std=c++11 build/ufbx-c11.o test/threadcheck.cpp -lm -o build/threadcheck-c11
          build/threadcheck-c11 data/maya_cube_7500_binary.fbx 2
      - name: Build and run threadcheck (standard C++11)
        run: |
          g++ -Wall -Wextra -Werror -pthread -std=c++11 -DUFBX_STANDARD_C -x c++ ufbx.c test/threadcheck.cpp -lm -o build/threadcheck-cpp11
          build/threadcheck-cpp11 data/maya_cube_7500_binary.fbx 2

  ci_wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install wasi-sdk
        run: |
          mkdir build
          export WASI_VERSION=14
          export WASI_VERSION_FULL=${WASI_VERSION}.0
          curl -L https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-${WASI_VERSION}/wasi-sdk-${WASI_VERSION_FULL}-linux.tar.gz -o build/wasi-sdk.tar.gz
          tar xzf build/wasi-sdk.tar.gz -C build
          mv build/wasi-sdk-${WASI_VERSION_FULL} build/wasi-sdk
      - name: Install wasmtime
        run: |
          curl https://wasmtime.dev/install.sh -sSf > wasmtime-install.sh
          bash wasmtime-install.sh --version v0.34.0
          echo "$HOME/.wasmtime/bin" >> $GITHUB_PATH
      - name: Test wasmtime
        run: wasmtime --version
      - name: Run tests
        run: python3 misc/run_tests.py tests --wasi-sdk build/wasi-sdk --compiler wasi_clang

  ci_arm32:
    runs-on: [self-hosted, ARM]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Run tests
        run: python3 misc/run_tests.py tests --no-sanitize --threads 2

  ci_arm64:
    runs-on: [self-hosted, ARM64]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Run tests
        run: python3 misc/run_tests.py tests --no-sanitize --threads 2

  ci_dataset:
    runs-on: [self-hosted, ARM64]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Create build directory
        run: mkdir build
      - name: Compile check_fbx.c
        run: clang -O2 test/check_fbx.c -lm -o build/check_fbx
      - name: Run dataset tests
        run: python3 misc/check_dataset.py --exe build/check_fbx --root /mnt/fbx-files --host-url https://ufbx-dataset.b-cdn.net

  ci_post_hashes:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [ci_ubuntu]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Compile hash_scene
        run: |
          mkdir build
          clang test/hash_scene.c misc/fdlibm.c -O2 -o build/hash_scene
      - uses: actions/download-artifact@v3
        with:
          name: hashdumps
          path: build/ci-hashdumps
      - name: List files to dump
        run: python3 misc/hash_diff.py list build/ci-hashdumps -o build/dumped-files.txt
      - name: Dump reference hashes
        run: |
          mkdir build/ref-hashdumps
          build/hash_scene --check build/dumped-files.txt --dump build/ref-hashdumps/reference_linux_x64_release.txt --dump-all
      - name: Compress reference hashdumps
        run: python3 misc/hash_diff.py compress build/ref-hashdumps -o build/hashdump_ci_reference.txt.gz
      - name: Diff CI and reference dumps
        run: python3 misc/hash_diff.py diff build/ci-hashdumps --ref build/hashdump_ci_reference.txt.gz
      - uses: actions/upload-artifact@v3
        if: ${{ always() && !cancelled() }}
        with:
          name: hashdumps
          path: build/hashdump_ci_reference.txt.gz
